### ISSUE TITLE
[QWIK-0.0.39] changeLocale(locale, ctx) results in eslint warning "Identifier ("ctx") can not be captured inside the scope [...]"

### ISSUE THREAD

**Issue by mahmoudajawad** [robisim74/qwik-speak#3]
Hello.

Using `qwik-speak` against newly created app that is using Qwik 0.0.39, and implement locale changing such as:
```tsx
onClick$={async () => await changeLocale(locale, ctx)}>
```
results in the following eslint warning:
```
[eslint] Identifier ("ctx") can not be captured inside the scope (onClick$) because "ctx.translateFn.getTranslation$" is a function, which is not serializable. Check out https://qwik.builder.io/docs/advanced/optimizer for more details. [qwik/valid-lexical-scope]
```
though, it seems to be working alright.

Would changing to using something like `ctx.setLocale(locale)` suppress this warning? I was looking into the lib code and there doesn't seem to be any blocker to moving that functionality to the context itself rather than creating a utility function for it.

**Comment by robisim74** [comment]
Hi @mahmoudajawad ,

thanks for reporting. The reason for this warning is not clear: I think it is a problem with Qwik linter rule, because it concerns another function `getTranslation$` that is actually serializable and is in the context.

In the meantime, to not see the warning, you can disable it in `.eslintrc.cjs`:

```
  rules: {
    ...
    'qwik/valid-lexical-scope': 'off'
  },
```

About `changeLocale`: it is an API of the library, I don't think it shoud be in the context. Instead, `setLocale` should contain your logic for saving the locale and for this reason it is in context.

**Comment by mahmoudajawad** [comment]
I'm fine with warning remaining as long as it is a linger issue which can be resolved later. I'm going to report this to Qwik team.

**Comment by robisim74** [comment]
Hi @mahmoudajawad ,

i release a fix https://github.com/robisim74/qwik-speak/commit/9be9d767aaf1ac461355763d127aa2a37a32d34f#diff-8f90d7374030007e4559573ed9b9d4f329eee714b37adb20fc4620d60268bd68 that solves the issue: it seems that the linter needs the QRL declaration to recognize functions as serializable.

Try the latest version, and let me know if it works as expected. Thanks

**Comment by mahmoudajawad** [comment]
This does definitely work. Thanks for working on it. Consider me as your early beta tester as I already am using qwik-speak for an app that I decided to develop with Qwik.
