### ISSUE TITLE
Cannot build the project and Extraction of the json file are done with value from the other lang json file, not the default value.

### ISSUE THREAD

**Issue by DongwonTTuna** [robisim74/qwik-speak#30]
To reproduce this error, I have created a simple qwik project at the following GitHub repository: https://github.com/DongwonTTuna/qwik-speak-ErrExample.git.

1. Firstly, please check the json files for each language. 
2. Next, please run `npm install && npm run dev` to confirm that it works as expected. 
3. Then, please try running `npm run build` to confirm that an error occurs. 
4. Finally, please use `npm run qwik-speak-extract` to confirm that the contents of each json file are overwritten with values in a different language other than the default values. (**this may need to run the command several times with original i18n files**)

Thank you!

**Comment by robisim74** [comment]
@DongwonTTuna thanks to your repro I was able to find the other two bugs that didn't make extracting and inlining work properly in the presence of objects.

They should be fixed in the latest release v.0.7.2.

**Note**. Even if it works, I must discourage you from using such complex objects in translations (depth > 1): it is out of the scope of this library (the purpose is to translate key-value pairs). After the build, the objects are inlined into the components for each language, resulting in very heavy components. I suggest rethinking the way you get items, and using the library to translate texts.

**Comment by DongwonTTuna** [comment]
Thank you for your prompt handling.

The issue has been completely resolved!

In addition, I will also reconsider the method you suggested, such as using a Set instead of a Map for implementation.

Thank you very much.😊
