### ISSUE TITLE
🩹 Problem with translations in arrays when rendering on client

### ISSUE THREAD

**Issue by devagja** [robisim74/qwik-speak#48]
Hi @robisim74,

First of all, thank you very much for all your effort and for offering us Qwik Speak.

When my component listings are rendered on the client while navigating through Qwik City's Link, do I need to include the runtimeAssets prop for it to work correctly?

The problem I encounter is that by adding runtimeAssets, the waiting time between page transitions increases significantly. In fact, I believe that currently it would take less time to query the page to the server than it takes for the resource to reach the browser and for Qwik Speak to perform the translations.

I'll leave a test repository here along with the corresponding deployments.

deploy without runtimeAssets -> https://speak-spa-runtime.vercel.app/
deploy with runtimeAssets -> https://speak-spa-runtime-git-withruntimeassets-joshxy.vercel.app/
Repo -> https://github.com/devagja/speak-spa-runtime

Thank you very much for everything!

**Comment by devagja** [comment]
To mention that it only happens with those translations that require certain prior logic before rendering, such as mapping a list.

**Comment by robisim74** [comment]
_When my component listings are rendered on the client while navigating through Qwik City's Link, do I need to include the runtimeAssets prop for it to work correctly?_ 

**The answer is no!**

You don't need `runtimeAssets` to use Link and SPA mode! `Inline` plugin works in both MPA and SPA because it replaces functions with translation values, and improve performance as you noticed!

Maybe I need to explain it even better in the documentation, but please read carefully: https://robisim74.gitbook.io/qwik-speak/tools/inline#build-using-qwik-speak-inline-vite-plugin-and-runtime

You still don't have dynamic keys in your app: if i do `npm run build` in your app, and open _qwik-speak-inline.log_ file, it does not report any dynamic or missing keys. Only single dynamic keys (obtained from variables) should be placed in the `runtimeAssets` files (as the name implies, these are evaluated at runtime).

That said, since there are multiple translation files, I suggest you to use the filename as root in your json files, e.g.:

_project.json_
```
{
  "project": {
    "minicast_description": "The goal of the test is to develop a mini-application for listening to music podcasts.",
    "minicast_description2": "Three views: main, podcast details, and chapter details.",
    ...
  }
}
```
otherwise, any equal keys will be overwritten because files are merged.

I hope that's clear now: I'll try to improve the documentation again anyway.

**Comment by devagja** [comment]
> You don't need `runtimeAssets` to use Link and SPA mode! `Inline` plugin works in both MPA and SPA because it replaces functions with translation values, and improve performance as you noticed!

Okey

What would be the correct way to translate keys within an array, then? Because the translations load correctly, but when they are nested within an array, for some reason, they lose the reference and don't get translated.

I'll use an example from my portfolio.
 https://github.com/devagja/speak-spa-runtime


_src\data\PROJECTS_LIST.tsx_
```
const PROJECTS_LIST = (t: any) => [
  {
    title: 'Minicast',
    descriptionList: t([
      'minicast_description',
      ...
    ]),
  ...
  }
]
```

_src\routes\[...lang]\demos\index.tsx_
```
import { Speak, $translate as t } from 'qwik-speak'
import PROJECTS_LIST from '~/data/PROJECTS_LIST'

export const Demos = component$(() => {

  return (
    <div class="flex flex-col gap-9 px-4 pb-32">
        {PROJECTS_LIST(t).map(
            ({ title, descriptionList }) => (
               <div key={title} class="hero ">
               ...
                 <span class="text-lg font-bold flex gap-2">
                     {t('requirements')}:
                 </span>
              ...
              <div>
             )
        )}
  </div>
  )
})

       
```

https://github.com/robisim74/qwik-speak/assets/43604808/e1b706c7-b53d-403b-8f03-a4c11b35ea6c

**Comment by robisim74** [comment]
You are passing the `$translate` as param to a function outside a Qwik `component$`, and the `Inline `plugin can't recognize it.

Because you can't use the `$translate` functions outside a `component$`, to avoid dynamic keys & `runtimeAssets`, you can use [$inlineTranslate ](https://robisim74.gitbook.io/qwik-speak/library/translate#usdinlinetranslate):

```
import { $inlineTranslate as t, type SpeakState } from 'qwik-speak'

const PROJECTS_LIST = (ctx: SpeakState) => [
  {
    title: 'Minicast',
    descriptionList: t([
      'minicast_description',
      'minicast_description2',
      'minicast_description3',
      'minicast_description4',
      'minicast_description5',
      'minicast_description6',
      'minicast_description7',
      'minicast_description8'
    ], ctx),
  }
]
```
and in component:
```
export const Demos = component$(() => {
  const ctx = useSpeakContext();

  return (
      {PROJECTS_LIST(ctx).map(
```

**Comment by devagja** [comment]
It works!!! Thank you very much @robisim74. I'm sorry for opening an issue when it's clearly defined in the documentation. Apologies.

I'm leaving the link to the documentation in case someone else makes the same mistake so I can help them.

https://robisim74.gitbook.io/qwik-speak/library/translate
