### ISSUE TITLE
QWIK ERROR Error: Code(20)

### ISSUE THREAD

**Issue by juanpmarin** [robisim74/qwik-speak#50]
Hi, I just upgraded qwik to 1.1.4 and qwik-speak ^0.13.0 with inline translation:
For production build I'm getting the following error:

`QWIK ERROR Error: Code(20)`

**Comment by robisim74** [comment]
@juanpmarin what you report is a Qwik error. Error 20 should be: _Calling a 'use*()' method outside 'component$ is not allowed_

It's wired that you don't get it already in development mode.

As for this library, check that you are not using a translation/localization function (except `$inlineTranslate`) outside a `component$`.

Does it work with versions before 0.13?

**Comment by juanpmarin** [comment]
It works correctly with qwik 1.1.1 and qwik-speak 0.12.0, as soon as I upgrade one of them, it breaks

**Comment by juanpmarin** [comment]
I double-checked my use of translate, and I'm only using it inside component$, I'm also using inlineTranslate in some places.

**Comment by robisim74** [comment]
The problem is using the function in component props. 

I think that in more recent versions of Qwik, the use of functions (with a context like `$translate`) in props should be avoided, you should prefer using a pure function like `$inlineTranslate `:

```
    const ctx = useSpeakContext();

    <div>
      <NavigationRailItem label={$inlineTranslate("app.menu.home@@Inicio", ctx)} active>
        <Icon>home</Icon>
      </NavigationRailItem>
    </div>
```

or translate in component:

```
    const label = t("app.menu.home@@Inicio"):

    <div>
      <NavigationRailItem label={label} active>
        <Icon>home</Icon>
      </NavigationRailItem>
    </div>
```
In both cases, the props becomes immutable.

I will update the docs.

**Comment by juanpmarin** [comment]
Thanks @robisim74, do you know why is this not recommended for props? Maybe some qwik docs

**Comment by robisim74** [comment]
Qwik optimizer transforms component props under the hood: they recently made some other changes (removing the functions props) and apparently `$translate` doesn't work anymore (`$translate `uses the `context` inside).

I'm looking for more stable solutions, but it's not simple: because Qwik keeps changing even if it's version 1.

For now, it is therefore preferable to avoid passing the `$translate` function in the component props.

**Comment by juanpmarin** [comment]
I understand, thanks for the explanation.

$inlineTranslate in props fixed the issue. Thanks!

**Comment by tom-bywild** [comment]
I'm experiencing a similar issue when trying to pass the result of a `t(...)` as prop to a `component$`, although Qwik now states that it can only accept serializable params.

I can't find any export of `$inlineTranslate`, was this function removed? I'm new to Qwik, so maybe I'm missing something regarding the special handling of `$`, should `inlineTranslate` be wrapped with it?

Either way, I'm currently using the following (ugly) workaround to get both generation of text + usage of translated text working (example component). tl;dr: I have to call `inlineTranslate` twice, first to make it visible to static generation, then to make it work as prop.

```jsx
export default component$(() => {
  const previews = usePreviews();
  const composeHref = useLocaleHrefComposer();

  const t = inlineTranslate();

  // This call gets picked up for static translation generation.
  t("app.nav.privacy@@Privacy");

  if (previews.value.failed) {
    return <div>Not found</div>;
  }

  return (
    <div class="relative flex h-screen snap-y snap-mandatory flex-col items-end gap-y-4 overflow-y-auto pb-80 pr-4 pt-4">
      <div class="fixed inset-y-0 left-0 flex h-screen flex-col-reverse items-start gap-y-4 p-10 text-sm font-light lowercase">
        <IconLink
          href={composeHref("/privacy")}
		  // Calling `inlineTranslate` directly here - works, but won't be added to `app.json`.
          alt={inlineTranslate()("app.nav.privacy@@Privacy")}
          Icon={inlinedQrl(LuShield, "lu-shield")}
          class="w-full"
        />
      </div>

      ...
    </div>
  );
});
```

Thanks for creating qwik-speak, it's awesome so far

**Comment by robisim74** [comment]
@tom-bywild This is an old issue, and yes,` $inlineTranslate` was removed in favor of `inlineTranslate`.

`alt={t("app.nav.privacy@@Privacy")}`

in your props should work. Maybe the problem is a conflict with `Icon` prop:

`Icon={inlinedQrl(LuShield, "lu-shield")}`

Did you try to remove it?

However, why `inlinedQrl`? it is an internal Qwik function. If you need, you should create a QRL using `$`, and declare a `PropFunction` in my opinion.

**Comment by tom-bywild** [comment]
Thanks for the quick reply, I'm still very React-minded, that's why `Icon` was intended to take an Icon-reference and render it via JSX itself, so that `IconLink` can be polymorphic.

I removed the prop and replaced it with a `<Slot name="icon" />`-implementation, which works nicely.

The issue with the translation still persists, though. 

I'll try to set up a demo project and see if I can replicate it their. If so, I'll update this thread, otherwise it's a weird issue somewhere in my code.

**Comment by tom-bywild** [comment]
just a quick follow-up, the error only seems to happen on the landing page (`/[...lang]/index.tsx`) when I mount the `IconLink`-component there as a direct child of the component.

If I move the logic into its own component (e.g. `NavColumn`) then it works fine. Not sure why, but I guess it's either a weird bug I made in my code, or a qwik-bug.

The result returned from the translate-function is always a primitive string, as I checked it with `typeof`. So I don't really understand why qwik is complaining that it can't be serialized - I don't think it should matter where I call the translate-function, as I don't provide it by reference but its result.

**Comment by robisim74** [comment]
> I don't think it should matter where I call the translate-function, as I don't provide it by reference but its result.

I agree: in JavaScript (and in every programming language) it's like this. But in Qwik it is an unresolved issue:

https://github.com/BuilderIO/qwik/issues/4371#issuecomment-1760146806
