### ISSUE TITLE
Dynamic key works on dev but not in production

### ISSUE THREAD

**Issue by juanpmarin** [robisim74/qwik-speak#51]
Hi! I'm trying to get translation using a dynamic key, like this:
https://github.com/juanpmarin/qwik-speak-repro/blob/0d0e053b1f92e08c3d7ca495b3926dda60b4ccee/src/components/list/list.tsx#L13

It works in development but no in production, you can see the bug here:
https://qwik-speak-repro.pages.dev/test/

If you press the **Add item** button, transition stop working

**Comment by robisim74** [comment]
Dynamic keys require `runtimeAssets`: https://robisim74.gitbook.io/qwik-speak/tools/inline#qwik-speak-inline-vite-plugin-and-runtime

**Comment by juanpmarin** [comment]
https://github.com/juanpmarin/qwik-speak-repro/commit/00bcd6affb580252a3a879f3a5f7abadb9ac3335

@robisim74 I've added runtime assets property and the bug still happens:
https://qwik-speak-repro.pages.dev/test/

**Comment by robisim74** [comment]
You are adding `app` asset twice: once in configuration as `runtimeAssets`, once as `assets` in https://github.com/juanpmarin/qwik-speak-repro/blob/master/src/routes/(internal)/layout.tsx

So you have to decide: either `app ` asset is shared by the whole app, or it's by scope.

That said, you should put only the keys you need in the runtime files, because they degrade performance if overused.

**Comment by juanpmarin** [comment]
@robisim74 thanks!

**Comment by juanpmarin** [comment]
@robisim74 translations with parameters like this one `shipments.order.recipient@@Envío para {{recipient}}` should be un runtime assets too?

**Comment by robisim74** [comment]
No. When you run the build for production, you will find translations with dynamic keys  in _qwik-speak-inline.log_
