### ISSUE TITLE
Bug: Code(3): Only primitive and object literals can be serialized

### ISSUE THREAD

**Issue by Zankel-Engineering** [robisim74/qwik-speak#57]
Hello,

I currently have the error above when using the library.
"version": "0.14.0",
"qwik": "1.1.4",
"qwik-city": "1.1.4"

QWIK ERROR Error: Code(3): Only primitive and object literals can be serialized
    at createError (D:/Zankel-Engineering/webpage/zankel-engineering/node_modules/@builder.io/qwik/core.mjs:108:17)
    at logError (D:/Zankel-Engineering/webpage/zankel-engineering/node_modules/@builder.io/qwik/core.mjs:102:54)
    at logErrorAndStop (D:/Zankel-Engineering/webpage/zankel-engineering/node_modules/@builder.io/qwik/core.mjs:112:17)
    at qError (D:/Zankel-Engineering/webpage/zankel-engineering/node_modules/@builder.io/qwik/core.mjs:185:12)
    at eval (D:/Zankel-Engineering/webpage/zankel-engineering/node_modules/@builder.io/qwik/core.mjs:2639:15)
    at Array.map (<anonymous>)
    at Module._pauseFromContexts (D:/Zankel-Engineering/webpage/zankel-engineering/node_modules/@builder.io/qwik/core.mjs:2603:32) 
    at beforeClose (D:/Zankel-Engineering/webpage/zankel-engineering/node_modules/@builder.io/qwik/server.mjs:451:52)
    at eval (D:/Zankel-Engineering/webpage/zankel-engineering/node_modules/@builder.io/qwik/core.mjs:3626:28)
    at eval (D:/Zankel-Engineering/webpage/zankel-engineering/node_modules/@builder.io/qwik/core.mjs:4111:25) [Function: translate]
    
Will try to update the lib, but I guess I have nearly the latest version. Do you have an idea what that is coming from?

I get this warning before:

Qwik Speak warn Locale not resolved. Fallback to default locale: de-DE

Sebastian

**Comment by robisim74** [comment]
Yes, I experienced the same error when using props. There are situations where if _mutable and immutable props_ are passed to the same component at the same time (and other unpredictable cases), Qwik throws this error difficult to debug.

Recent issues in Qwik repo: https://github.com/BuilderIO/qwik/issues/4371, https://github.com/BuilderIO/qwik/issues/4038

Please note that since v0.14.0, this library uses a hook that respects all the rules, and returns a closure that is a pure function, which Qwik interprets as immutable.

**Comment by Zankel-Engineering** [comment]
Hi Robi,

I use the hook and still have the error.

Will look into it further tomorrow.

Sebastian

Roberto Simonetti ***@***.***> schrieb am Mo., 29. Mai 2023,
21:35:

**Comment by Zankel-Engineering** [comment]
Hi Robi,

this is in the translation[lang] at the end:  [Symbol(Symbol.toStringTag)]: 'Module'

Should that be there? Do you know where it is coming from?

Sebastian

**Comment by robisim74** [comment]
The error is with using the hook in component `props` along with other functions (but only in some cases that it is also difficult to reproduce and locate) - look in the issues I referenced.

`[Symbol(Symbol.toStringTag)]: 'Module'` that is one of the many transformations done by Qwik (in this case `context`)

**Comment by Zankel-Engineering** [comment]
Hi Robi,

I am afraid but I have not used any hook outside the bounds of $component.
I can give you access to the repo if you want to take a look at it?

Sebastian

Am Mo., 29. Mai 2023 um 23:12 Uhr schrieb Roberto Simonetti <
***@***.***>:

**Comment by robisim74** [comment]
Yes, if you have a repo I can look into it.

But the error doesn't happen if you use the hook outside the bounds of `component$`, it usually happens when you pass the hook into the components `props`. For example, if in this library's sample app I do:

`<Link href={getHref('/')} title={t('app.title')}>`

I get `Code(3): Only primitive and object literals can be serialized`

In this example, `getHref `is a _mutable_ function, while `t` is _immutable_: if you remove one, the error disappears.

In my opinion, this is a bug in Qwik, reported in the issues I referenced above.

**Comment by Zankel-Engineering** [comment]
Crazy. I have send you an invite. I am not sure if I understand what you
mean. It can be that it is because of the click$ PropFunction passed to the
button component then?

The error messages are really not good there.

Am Di., 30. Mai 2023 um 18:33 Uhr schrieb Roberto Simonetti <
***@***.***>:

**Comment by robisim74** [comment]
Hi Sebastian,

I had a look at your project: as I supposed the problem is in multiple props, in your case when you use `Button` and `Video `components.

In both cases, in order not to give up on functionality, the workaround for now is to translate before passing the prop:

```
const text = t('header.meeting');

<Button
    text={text}
    click$={meeting$}
    type="primary"
    clazzes="mr-4"
></Button>
```

```
const text = t(`${type}.networkSection.video`)

<Video
    src="xxx"
    banner={{ text: text }}
/>
```
In the latter case, I think the problem is caused by the hook `type `inside the `t` hook, passed as `prop`...

I think you should try to reproduce the problem on a small project, and open an issue on the Qwik repo, because these errors are really annoying, they're weird and they're badly reported.

**Comment by Zankel-Engineering** [comment]
Hi Robi, thanks. I will do that tomorrow. Sebastian Gesendet von Mail für Windows Von: Roberto SimonettiGesendet: Dienstag, 30. Mai 2023 22:41An: robisim74/qwik-speakCc: Zankel-Engineering; AuthorBetreff: Re: [robisim74/qwik-speak] Bug: Code(3): Only primitive and object literals can be serialized (Issue #57) Hi Sebastian,I had a look at your project: as I supposed the problem is in multiple props, in your case when you use Button and Video components.In both cases, in order not to give up on functionality, the workaround for now is to translate before passing the prop:const text = t('header.meeting'); <Button    text={text}    click$={meeting$}    type="primary"    clazzes="mr-4"></Button>const text = t(`${type}.networkSection.video`) <Video    src="xxx"    banner={{ text: text }}/>In the latter case, I think the problem is caused by the hook type inside the t hook, passed as prop...I think you should try to reproduce the problem on a small project, and open an issue on the Qwik repo, because these errors are really annoying, they're weird and they're badly reported.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Zankel-Engineering** [comment]
Hi Robi can you give me a hint where exactly the problem is in the lib? I would like to understand it.

**Comment by robisim74** [comment]
See above: https://github.com/robisim74/qwik-speak/issues/57#issuecomment-1567454367

**Comment by ahnpnl** [comment]
The workaround I think can also extend to be a polymorphic component. For example user can pass in html tag name and translation key as props.

**Comment by robisim74** [comment]
This issue should no longer occur from version 0.17.0, since the new `inlineTransate` and `inlinePlural` functions no longer use the context.

Greetings
